name: Arcade
run-name: Mirroring to main 

on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
      - 'https://github.com/EpitechPromo2028/B-OOP-400-PAR-4-1-arcade-pierre.pruvost'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'
      - 'https://github.com/EpitechPromo2028/B-OOP-400-PAR-4-1-arcade-pierre.pruvost'

env:
  MIRROR_URL: 'git@github.com:EpitechPromo2028/B-OOP-400-PAR-4-1-arcade-pierre.pruvost.git'
  EXECUTABLES: 'arcade'

jobs:
  check_program_compilation:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    timeout-minutes: 2
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - run: rm -f ${{ env.EXECUTABLES }}
      - run: ./compile.sh -re
      - run: ls
      - run: if [ ! -f "./${{ env.EXECUTABLES }}" ]; then exit 1; fi

  push_to_mirror:
    needs: [check_program_compilation]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}